import { connect } from 'react-redux'
import { push } from 'react-router-redux'

import Questionnaire from 'components/Questionnaire'
import { selectAnswer } from '../actions/questionnaire'

const mapStateToProps = ({ questionnaire }) => {
  return questionnaire
}

const mapDispatchToProps = (dispatch) => {
  return {
    onAnswerClick: (questionId, answerId) => {
      dispatch(selectAnswer(questionId, answerId))
    },
    onSubmit: () => {
      dispatch(push('/results'))
    }
  }
}

// The components in this directory are container components generated by
// react-redux. They wrap the React components, handling Redux state and actions.
const AnsweredQuestionnaire = connect(
  mapStateToProps,
  mapDispatchToProps
  // React component
)(Questionnaire)

export default AnsweredQuestionnaire
